2019-01-03 20:02:10,014 ERROR: Exception on /login [GET] [in /home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/app/routes.py", line 33, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/app/templates/base.html", line 51, in template
    {% endblock %}
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/app/templates/base.html", line 51, in template
    {% endblock %}
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/venv/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2019-01-03 20:04:51,128 INFO: Microblog startup [in /home/gene/Desktop/DESKTOP/DESKTOP/groupfrontend/app/__init__.py:49]
